config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :resources

  resources :buyer_profiles

  resources :business_plans

  resources :marketing_plans

  resources :sections

  resources :swots

  root 'landings#index'

end

app/models/marketing_plan.rb
class MarketingPlan < ActiveRecord::Base
  belongs_to :buyer_profile
end

app/controllers/marketing_plans_controller.rb
class MarketingPlansController < ApplicationController
  before_action :set_marketing_plan, only: [:show, :edit, :update, :destroy]

  # GET /marketing_plans
  # GET /marketing_plans.json
  def index
    @marketing_plans = MarketingPlan.all
  end

  # GET /marketing_plans/1
  # GET /marketing_plans/1.json
  def show
  end

  # GET /marketing_plans/new
  def new
    @marketing_plan = MarketingPlan.new
  end

  # GET /marketing_plans/1/edit
  def edit
  end

  # POST /marketing_plans
  # POST /marketing_plans.json
  def create
    @marketing_plan = MarketingPlan.new(marketing_plan_params)

    respond_to do |format|
      if @marketing_plan.save
        format.html { redirect_to @marketing_plan, notice: 'Marketing plan was successfully created.' }
        format.json { render :show, status: :created, location: @marketing_plan }
      else
        format.html { render :new }
        format.json { render json: @marketing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketing_plans/1
  # PATCH/PUT /marketing_plans/1.json
  def update
    respond_to do |format|
      if @marketing_plan.update(marketing_plan_params)
        format.html { redirect_to @marketing_plan, notice: 'Marketing plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @marketing_plan }
      else
        format.html { render :edit }
        format.json { render json: @marketing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketing_plans/1
  # DELETE /marketing_plans/1.json
  def destroy
    @marketing_plan.destroy
    respond_to do |format|
      format.html { redirect_to marketing_plans_url, notice: 'Marketing plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marketing_plan
      @marketing_plan = MarketingPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marketing_plan_params
      params.require(:marketing_plan).permit(:buyer_profile_id, :title, :value_proposition, :objective, :plan_desc, :type_of_activity, :start_date, :end_date, :implementation_team, :estimated_budget, :media_strat, :distro_channels, :milestone_of_completion, :success_indicator, :monitor_method, :outcomes, :appendix_additional)
    end
end

app/helpers/marketing_plans_helper.rb
module MarketingPlansHelper
end

app/views/marketing_plans/_form.html.erb
<%= form_for @marketing_plan, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value_proposition, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :value_proposition, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :objective, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :objective, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :plan_desc, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :plan_desc, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type_of_activity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :type_of_activity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :start_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :end_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :implementation_team, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :implementation_team, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :estimated_budget, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :estimated_budget, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :media_strat, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :media_strat, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :distro_channels, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :distro_channels, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :milestone_of_completion, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :milestone_of_completion, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :success_indicator, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :success_indicator, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :monitor_method, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :monitor_method, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :outcomes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :outcomes, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :appendix_additional, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :appendix_additional, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  marketing_plans_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/marketing_plans/edit.html.erb
<%- model_class = MarketingPlan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MarketingPlan %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marketing_plans/index.html.erb
<%- model_class = MarketingPlan -%>
<div class="page-header">
  <h1><%=t '.title', :default => MarketingPlan %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:value_proposition) %></th>
      <th><%= model_class.human_attribute_name(:objective) %></th>
      <th><%= model_class.human_attribute_name(:plan_desc) %></th>
      <th><%= model_class.human_attribute_name(:type_of_activity) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:implementation_team) %></th>
      <th><%= model_class.human_attribute_name(:estimated_budget) %></th>
      <th><%= model_class.human_attribute_name(:media_strat) %></th>
      <th><%= model_class.human_attribute_name(:distro_channels) %></th>
      <th><%= model_class.human_attribute_name(:milestone_of_completion) %></th>
      <th><%= model_class.human_attribute_name(:success_indicator) %></th>
      <th><%= model_class.human_attribute_name(:monitor_method) %></th>
      <th><%= model_class.human_attribute_name(:outcomes) %></th>
      <th><%= model_class.human_attribute_name(:appendix_additional) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @marketing_plans.each do |marketing_plan| %>
      <tr>
        <td><%= marketing_plan.id %></td>
        <td><%= marketing_plan.title %></td>
        <td><%= marketing_plan.value_proposition %></td>
        <td><%= marketing_plan.objective %></td>
        <td><%= marketing_plan.plan_desc %></td>
        <td><%= marketing_plan.type_of_activity %></td>
        <td><%= marketing_plan.start_date %></td>
        <td><%= marketing_plan.end_date %></td>
        <td><%= marketing_plan.implementation_team %></td>
        <td><%= marketing_plan.estimated_budget %></td>
        <td><%= marketing_plan.media_strat %></td>
        <td><%= marketing_plan.distro_channels %></td>
        <td><%= marketing_plan.milestone_of_completion %></td>
        <td><%= marketing_plan.success_indicator %></td>
        <td><%= marketing_plan.monitor_method %></td>
        <td><%= marketing_plan.outcomes %></td>
        <td><%= marketing_plan.appendix_additional %></td>
        <td><%=l marketing_plan.created_at, format: :long %></td>
        <td>
          <%= link_to marketing_plan_path(marketing_plan), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to marketing_plan_path(marketing_plan), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_marketing_plan_path,
            :class => 'btn btn-primary' %>

app/views/marketing_plans/new.html.erb
<%- model_class = MarketingPlan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MarketingPlan %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marketing_plans/show.html.erb
<%- model_class = MarketingPlan -%>
<div class="page-header">
  <h1><%=t '.title', :default => MarketingPlan %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value_proposition) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.value_proposition %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:objective) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.objective %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:plan_desc) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.plan_desc %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type_of_activity) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.type_of_activity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_date) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.start_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:end_date) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.end_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:implementation_team) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.implementation_team %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:estimated_budget) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.estimated_budget %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:media_strat) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.media_strat %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:distro_channels) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.distro_channels %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:milestone_of_completion) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.milestone_of_completion %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:success_indicator) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.success_indicator %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:monitor_method) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.monitor_method %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:outcomes) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.outcomes %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:appendix_additional) %></dt>
      <dd><pre class="prettyprint"><%= @marketing_plan.appendix_additional %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              marketing_plans_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_marketing_plan_path(@marketing_plan), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              marketing_plan_path(@marketing_plan),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>