config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :resources

  resources :buyer_profiles

  resources :business_plans

  resources :marketing_plans

  resources :sections

  resources :swots

  root 'landings#index'

end

app/models/swot.rb
class Swot < ActiveRecord::Base
end

app/controllers/swots_controller.rb
class SwotsController < ApplicationController
  before_action :set_swot, only: [:show, :edit, :update, :destroy]

  # GET /swots
  # GET /swots.json
  def index
    @swots = Swot.all
  end

  # GET /swots/1
  # GET /swots/1.json
  def show
  end

  # GET /swots/new
  def new
    @swot = Swot.new
  end

  # GET /swots/1/edit
  def edit
  end

  # POST /swots
  # POST /swots.json
  def create
    @swot = Swot.new(swot_params)

    respond_to do |format|
      if @swot.save
        format.html { redirect_to @swot, notice: 'Swot was successfully created.' }
        format.json { render :show, status: :created, location: @swot }
      else
        format.html { render :new }
        format.json { render json: @swot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swots/1
  # PATCH/PUT /swots/1.json
  def update
    respond_to do |format|
      if @swot.update(swot_params)
        format.html { redirect_to @swot, notice: 'Swot was successfully updated.' }
        format.json { render :show, status: :ok, location: @swot }
      else
        format.html { render :edit }
        format.json { render json: @swot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swots/1
  # DELETE /swots/1.json
  def destroy
    @swot.destroy
    respond_to do |format|
      format.html { redirect_to swots_url, notice: 'Swot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swot
      @swot = Swot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swot_params
      params.require(:swot).permit(:company_name, :strength, :weak, :opportunity, :threat)
    end
end

app/helpers/swots_helper.rb
module SwotsHelper
end

app/views/swots/_form.html.erb
<%= form_for @swot, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :company_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :strength, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :strength, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :weak, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :weak, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :opportunity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :opportunity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :threat, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :threat, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  swots_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/swots/edit.html.erb
<%- model_class = Swot -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Swot %></h1>
</div>
<%= render :partial => 'form' %>

app/views/swots/index.html.erb
<%- model_class = Swot -%>
<div class="page-header">
  <h1><%=t '.title', :default => Swot %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:strength) %></th>
      <th><%= model_class.human_attribute_name(:weak) %></th>
      <th><%= model_class.human_attribute_name(:opportunity) %></th>
      <th><%= model_class.human_attribute_name(:threat) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @swots.each do |swot| %>
      <tr>
        <td><%= swot.id %></td>
        <td><%= swot.company_name %></td>
        <td><%= swot.strength %></td>
        <td><%= swot.weak %></td>
        <td><%= swot.opportunity %></td>
        <td><%= swot.threat %></td>
        <td><%=l swot.created_at, format: :long %></td>
        <td>
          <%= link_to swot_path(swot), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to swot_path(swot), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_swot_path,
            :class => 'btn btn-primary' %>

app/views/swots/new.html.erb
<%- model_class = Swot -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Swot %></h1>
</div>
<%= render :partial => 'form' %>

app/views/swots/show.html.erb
<%- model_class = Swot -%>
<div class="page-header">
  <h1><%=t '.title', :default => Swot %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_name) %></dt>
      <dd><pre class="prettyprint"><%= @swot.company_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:strength) %></dt>
      <dd><pre class="prettyprint"><%= @swot.strength %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:weak) %></dt>
      <dd><pre class="prettyprint"><%= @swot.weak %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:opportunity) %></dt>
      <dd><pre class="prettyprint"><%= @swot.opportunity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:threat) %></dt>
      <dd><pre class="prettyprint"><%= @swot.threat %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              swots_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_swot_path(@swot), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              swot_path(@swot),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>