config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :resources

  resources :buyer_profiles

  resources :business_plans

  resources :marketing_plans

  resources :sections

  resources :swots

  root 'landings#index'

end

app/models/buyer_profile.rb
class BuyerProfile < ActiveRecord::Base
  has_many :marketing_plans
end

app/controllers/buyer_profiles_controller.rb
class BuyerProfilesController < ApplicationController
  before_action :set_buyer_profile, only: [:show, :edit, :update, :destroy]

  # GET /buyer_profiles
  # GET /buyer_profiles.json
  def index
    @buyer_profiles = BuyerProfile.all
  end

  # GET /buyer_profiles/1
  # GET /buyer_profiles/1.json
  def show
  end

  # GET /buyer_profiles/new
  def new
    @buyer_profile = BuyerProfile.new
  end

  # GET /buyer_profiles/1/edit
  def edit
  end

  # POST /buyer_profiles
  # POST /buyer_profiles.json
  def create
    @buyer_profile = BuyerProfile.new(buyer_profile_params)

    respond_to do |format|
      if @buyer_profile.save
        format.html { redirect_to @buyer_profile, notice: 'Buyer profile was successfully created.' }
        format.json { render :show, status: :created, location: @buyer_profile }
      else
        format.html { render :new }
        format.json { render json: @buyer_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyer_profiles/1
  # PATCH/PUT /buyer_profiles/1.json
  def update
    respond_to do |format|
      if @buyer_profile.update(buyer_profile_params)
        format.html { redirect_to @buyer_profile, notice: 'Buyer profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer_profile }
      else
        format.html { render :edit }
        format.json { render json: @buyer_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyer_profiles/1
  # DELETE /buyer_profiles/1.json
  def destroy
    @buyer_profile.destroy
    respond_to do |format|
      format.html { redirect_to buyer_profiles_url, notice: 'Buyer profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer_profile
      @buyer_profile = BuyerProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_profile_params
      params.require(:buyer_profile).permit(:name, :description, :buyer_goals, :target_features, :potential_hesitations, :acquisition_location)
    end
end

app/helpers/buyer_profiles_helper.rb
module BuyerProfilesHelper
end

app/views/buyer_profiles/_form.html.erb
<%= form_for @buyer_profile, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :buyer_goals, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :buyer_goals, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :target_features, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :target_features, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :potential_hesitations, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :potential_hesitations, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :acquisition_location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :acquisition_location, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  buyer_profiles_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/buyer_profiles/edit.html.erb
<%- model_class = BuyerProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => BuyerProfile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/buyer_profiles/index.html.erb
<%- model_class = BuyerProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => BuyerProfile %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:buyer_goals) %></th>
      <th><%= model_class.human_attribute_name(:target_features) %></th>
      <th><%= model_class.human_attribute_name(:potential_hesitations) %></th>
      <th><%= model_class.human_attribute_name(:acquisition_location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @buyer_profiles.each do |buyer_profile| %>
      <tr>
        <td><%= buyer_profile.id %></td>
        <td><%= buyer_profile.name %></td>
        <td><%= buyer_profile.description %></td>
        <td><%= buyer_profile.buyer_goals %></td>
        <td><%= buyer_profile.target_features %></td>
        <td><%= buyer_profile.potential_hesitations %></td>
        <td><%= buyer_profile.acquisition_location %></td>
        <td><%=l buyer_profile.created_at, format: :long %></td>
        <td>
          <%= link_to buyer_profile_path(buyer_profile), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to buyer_profile_path(buyer_profile), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_buyer_profile_path,
            :class => 'btn btn-primary' %>

app/views/buyer_profiles/new.html.erb
<%- model_class = BuyerProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => BuyerProfile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/buyer_profiles/show.html.erb
<%- model_class = BuyerProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => BuyerProfile %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:buyer_goals) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.buyer_goals %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:target_features) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.target_features %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:potential_hesitations) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.potential_hesitations %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:acquisition_location) %></dt>
      <dd><pre class="prettyprint"><%= @buyer_profile.acquisition_location %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              buyer_profiles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_buyer_profile_path(@buyer_profile), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              buyer_profile_path(@buyer_profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>